# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa3c9c0b45808ac10ab637dae82761b413bbcb78230687b313e3a3846f233c8950d473016f22766ddeaa4e5caaa62864fc53f91948717b965330c16f51802180

test:
  secret_key_base: 0a6d5f698ab7605cfd1a6979c6557a8b6089bde68e4e2c69e327a57814f49576243286c1ba00d12fd644f31b58c96566771589c8f284669bc7fa6f70ef805ed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
